import { Inter } from "next/font/google";
import "./globals.css";
import MobileHeader from "./components/MobileHeader";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`w-full bg-red-500 ${inter.className}`}>
        <MobileHeader />

        {children}
        <Footer/>

        </body>
    </html>
  );
}
